version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bookstore
volumes:
  mongodb_data_container:
