version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bookstore
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongodb_data_container:
