spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    async:
      request-timeout: 300000
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookstore
  jpa:
    show-sql: 'true'
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /bookstore
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
csv-import:
  authors-file-path: src/main/resources/csv/authors.csv
  books-file-path: src/main/resources/csv/books.csv
  export-file-path: src/main/resources/csv
  batch-size: 100000
