spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookstore
  jpa:
    show-sql: 'true'
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /bookstore
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs


